# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "documents", :force => true do |t|
    t.column "type", :string
    t.column "title", :string
    t.column "raw_text", :text
    t.column "formatted_text", :text
    t.column "created_on", :datetime
    t.column "edited_on", :datetime
  end

  create_table "links", :force => true do |t|
    t.column "document_id", :integer
    t.column "title", :string
    t.column "exists", :boolean
  end

  create_table "taggings", :force => true do |t|
    t.column "taggable_id", :integer
    t.column "tag_id", :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "display_name", :string
    t.column "password_salt", :string
    t.column "password_hash", :string
  end

end
